.TH NGCP-API-DELETE 1
.SH NAME
ngcp-api-delete \- sends a delete request to NGCP REST API
.SH SYNOPSIS
.B ngcp-api-delete
[\fB\-v\fR]
[\fB\-h\fR]
.I URL
.SH DESCRIPTION
.B ngcp-api-delete
sends a delete request to NGCP REST API.
.SH OPTIONS
.TP
.BR \-v
Verbose mode.
.TP
.BR \-h
Print usage.
.TP
.I URL
URL for the request.
.SH EXAMPLES
.EX
$ ngcp-api-delete 'https://example.org:1443/api/domains/1'
.EE
.SH SEE ALSO
.BR ngcp-api-put (1),
.BR ngcp-api-post (1),
.BR ngcp-api-patch (1),
.BR ngcp-api-get (1).
.PP
https://ngcp-server.domain:1443/api
.SH COPYRIGHT
2014 Sipwise Development Team <support@sipwise.com>
