.TH NGCP-API-PATCH 1
.SH NAME
ngcp-api-patch \- sends a patch request to NGCP REST API
.SH SYNOPSIS
.B ngcp-api-patch
[\fB\-f\fR \fIFILEPATH\fR]
[\fB\-m\fR]
[\fB\-v\fR]
[\fB\-h\fR]
.IR URL
.SH DESCRIPTION
.B ngcp-api-patch
sends a patch request to NGCP REST API.
.SH OPTIONS
.TP
.BI \-f " FILEPATH"
Use
.I FILEPATH
as input file instead of stdin.
.TP
.B \-m
Use the Header 'Refer: return=minimal'.
Default is 'Refer: return=representation'
.TP
.B \-v
Verbose mode.
.TP
.B \-h
Print usage.
.TP
.I URL
URL for the request.
.SH EXAMPLES
.EX
$ echo '[ { "op" : "remove", "path" : "/active" } ]'\\
| ngcp-api-patch 'https://example.org:1443/api/faxserversettings/2'
.EE
.SH SEE ALSO
.BR ngcp-api-put (1),
.BR ngcp-api-post (1),
.BR ngcp-api-delete (1),
.BR ngcp-api-get (1).
.PP
https://ngcp-server.domain:1443/api
.SH COPYRIGHT
2014 Sipwise Development Team <support@sipwise.com>
