.TH NGCP-API-PUT 1
.SH NAME
ngcp-api-put \- sends a put request to NGCP REST API
.SH SYNOPSIS
.B ngcp-api-put
[\fB\-f\fR \fIFILEPATH\fR]
[\fB\-v\fR]
[\fB\-h\fR]
.IR URL
.RI [ CONTENT-TYPE ]
.SH DESCRIPTION
.B ngcp-api-put
sends a put request to NGCP REST API.
.SH OPTIONS
.TP
.BI \-f " FILEPATH"
Use
.I FILEPATH
as input file instead of stdin.
.TP
.B \-v
Verbose mode.
.TP
.B \-h
Print usage.
.TP
.I URL
URL for the request
.TP
.I CONTENT-TYPE
Specifies the HTTP content-type.
The default is 'application/json'
.SH EXAMPLES
.EX
$ echo '{"body":"test","from_email":"test","name":"test","reseller_id":4,"subject":"test"}'\\
| ngcp-api-put 'https://example.org:1443/api/emailtemplates/2'
.EE
.PP
.EX
$ ngcp-api-put -f ../test_put.json https://127.0.0.1:1443/api/domains/ 'application/json'
.EE
.SH SEE ALSO
.BR ngcp-api-get (1),
.BR ngcp-api-post (1),
.BR ngcp-api-patch (1),
.BR ngcp-api-delete (1).
.PP
https://ngcp-server.domain:1443/api
.SH COPYRIGHT
2014 Sipwise Development Team <support@sipwise.com>
