.TH NGCP-API-GET 1
.SH NAME
ngcp-api-get \- sends a get request to NGCP REST API
.SH SYNOPSIS
.B ngcp-api-get
[\fB\-v\fR]
[\fB\-h\fR]
.IR URL
.SH DESCRIPTION
.B ngcp-api-get
sends a get request to NGCP REST API.
.SH OPTIONS
.TP
.B \-v
Verbose mode.
.TP
.B \-h
Print usage.
.TP
.I URL
URL for the request.
.SH EXAMPLES
.EX
$ ngcp-api-get 'https://example.org:1443/api/domains/'
.EE
.SH SEE ALSO
.BR ngcp-api-put (1),
.BR ngcp-api-post (1),
.BR ngcp-api-patch (1),
.BR ngcp-api-delete (1).
.PP
https://ngcp-server.domain:1443/api
.SH COPYRIGHT
2014 Sipwise Development Team <support@sipwise.com>
