.TH NGCP-API 1
.SH NAME
sends a patch request to NGCP REST API
.SH SYNOPSIS
.B ngcp-api-patch
[\fB\-f\fR \fIFILEPATH\fR]
[\fB\-m\fR]
[\fB\-v\fR]
[\fB\-h\fR]
.IR URL
.SH DESCRIPTION
.B ngcp-api-patch
sends a patch request to NGCP REST API.
.SH OPTIONS
.TP
.BR \-f " " \fIFILEPATH\fR
use input file instead of stdin.
.TP
.BR \-m
Use Header 'Refer: return=minimal'. Default is 'Refer: return=representation'
.TP
.BR \-v
verbose mode.
.TP
.BR \-h
print usage.
.TP
URL
Url for the request
.SH EXAMPLES
.TP
echo '[ { "op" : "remove", "path" : "/active" } ]'|\\
ngcp-api-patch 'https://example.org:1443/api/faxserversettings/2'
.SH SEE ALSO
.TP
ngcp-api-put(1), ngcp-api-post(1), ngcp-api-delete(1), ngcp-api-get(1)
.TP
https://ngcp-server.domain:1443/api
.SH COPYRIGHT
2014 Sipwise Development Team <support@sipwise.com>
