#!/bin/bash
# This script is used for running the tests with
# proper arguments from Jenkins under user 'selenium'

set -e

su - selenium -c "cd /code && ./t/selenium/testrunner $*" || RC=$?

## Mask non-zero exit code here
## Jenkins will detect errors in produced artifacts if any
## as a result the Jenkins job will be "yellow" instead of "red".
exit 0 # ${RC:-0}
