#!/usr/bin/env perl
use Convert::Ascii85 qw();
use IO::Uncompress::UnXz qw(unxz $UnXzError);

local $/ = undef;
my $buf = Convert::Ascii85::decode(<>);
my $out;
unxz \$buf, \$out or die $UnXzError;
print $out;

__END__

=encoding UTF-8

=head1 NAME

ngcp_panel_decode_crash - decode a crash state from the Web server error log

=head1 USAGE

    ngcp_panel_decode_crash < crashfile
