#!/bin/bash

if ! [ -f /.dockerinit ]; then
  echo "Not running inside docker, exiting to avoid data damage." >&2
  exit 1
fi

set -e
set -u

if [ -z "${1:-}" ] ; then
  echo "Usage: $0 <testsystem>" >&2
  echo
  echo "Usage example: $0 192.168.88.162"
  exit 1
fi

if [[ $2 == "active" ]]; then
  SELECT=active;
elif [[ $2 == "fast" ]]; then
    SELECT=fast;
fi

SERVER="${1}"

if [ -z "${SELECT:-}" ] ; then
  SELECT=$(echo t/api-rest/*.t)
elif [[ $SELECT == "active"  ]]; then
  SELECT=$(echo t/api-rest/api-{billingfees,billingnetworks,billingprofiles,billingzones,calllists,calls,cert-auth,cfdestinationsets,ncoslevels,pbxdevicemodels,pbxdevices,peeringgroups,peeringrules,peeringservers,preferences,profilepackages,resellers,rewriterules,soundsets,subscriberregistrations,subscribers,systemcontacts,threads,topuplogs,trustedsources,valid-patch,vouchers}.t)
elif [[ $SELECT == "fast" ]]; then
  SELECT=$(echo t/api-rest/api-{billingnetworks,billingzones,calls,cert-auth,cfdestinationsets,ncoslevels,peeringgroups,peeringrules,peeringservers,resellers,rewriterules,soundsets,systemcontacts,valid-patch,vouchers}.t)
fi

echo "################################################################################"
echo "Finished main setup, now running tests ..."
RC=0
# api-threads.t and api-balanceintervals.t are failing with the "-Pretty option" :(
CATALYST_SERVER="https://${SERVER}:1443" prove -v --color -l -It/lib \
                  $SELECT | tee -a /code/api-rest.pretty || RC=$?
#CATALYST_SERVER="https://${SERVER}:1443" prove --formatter TAP::Formatter::JUnit -l -It/lib $SELECT | tee -a /code/api-rest.xml || RC=$?
echo "Finished test execution, test execution returned with exit code ${RC}."
for file in /code/api-rest.pretty /code/api-rest.xml ; do
  if [ -f "$file" ] ; then
    echo "Test results available at ${file}"
  fi
done
echo "################################################################################"
